### ISSUE TITLE
Lower FSharp.Core dependency from 6.0.0 to 4.7.2 for better compatibility

### ISSUE THREAD

**Issue by Zaid-Ajaj** [fable-compiler/Fable.Python#19]
Fable.Python right now depends on FSharp.Core v6.0.0 which means that existing projects might need to update their FSharp.Core version when using Fable.Python package. Is it possible to lower the required version of FSharp.Core to 4.7.2 for best compatiblity? especially given the fact that this bindings library doesn't require latest F# features iirc

**Comment by dbrattli** [comment]
I thought I had limited it to 5 by using `>= 5` but I guess it doesn't work that way. Setting it to `~> 4.7` instead.
