### ISSUE TITLE
JSON serialization

### ISSUE THREAD

**Issue by thautwarm** [fable-compiler/Fable.Python#27]
I'd like to access [FSharp.Json](https://github.com/vsapronov/FSharp.Json/tree/master/FSharp.Json) or any Fable.Python equivalent. However, the transpiler seems omitting the `FSharp.Json` dependency and I got an undefined variable `FSharp_Json_Json_serialize` in my generated python source.

The reflection information in the generated python code seems sufficient to support `FSharp.Json`, hence I wonder if I can get `FSharp.Json` work or get any alternative?

**Comment by dbrattli** [comment]
I don't think this library would work with Fable without any modification. Do you know if it works with Fable (JavaScript)? There is [Fable.SimpleJson.Python](https://github.com/Zaid-Ajaj/Fable.SimpleJson.Python) and [Fable.Python.Json](https://github.com/fable-compiler/Fable.Python/blob/main/test/TestJson.fs) builtin that should work

**Comment by thautwarm** [comment]
>  Do you know if it works with Fable (JavaScript)?

No, `FSharp.Json` doesn't work with Fable.

> ... Fable.SimpleJson.Python and Fable.Python.Json builtin that should work

Thanks, these work.
