### ISSUE TITLE
incorrect code generation for `List.RemoveAt`

### ISSUE THREAD

**Issue by thautwarm** [fable-compiler/Fable.Python#31]
For `List.RemoveAt(i: int)` in F\#, I got `list.pop(i, 1)` in Python..

repro code:

```fsharp
type System.Collections.Generic.List<'a> with
    member this.Last = this.[this.Count - 1]
    member this.Pop() =
            let i = this.Count - 1
            let r = this.[i]
            this.RemoveAt(i)
            r
```

-> 
```python
def System_Collections_Generic_List_1__List_1_Pop(this: List[T]) -> T:
    i : int = (len(this) - 1) or 0
    r : T = this[i]
    this.pop(i, 1)     <---- incorrect here
    return r

```

P.S: It does not stuck my works as I can change the impl, but I'd like to know to contribute to Fable.Python compiler itself. 

IIRC fable-python was already merged into the fable compiler repo, but now I cannot find anything about it. When you have time, please give me some necessary instructions about developing the fable-python compiler.

**Comment by thautwarm** [comment]
I positioned the bug: https://github.com/dbrattli/Fable/blob/8d14c7082799e288bd14793326fa2b3f5f54adb5/src/Fable.Transforms/Python/Replacements.fs#L1889

I wonder how could I submit a PR for Fable.Python? Which branch should I target? 
I saw you were wokring on multiple branches, which is pretty good. However, it seems that we don't have a `main` branch for the works...?

**Comment by dbrattli** [comment]
That is correct. The new languages (Python, Rust, ...) works against the `beyond` [branch](https://github.com/fable-compiler/Fable/tree/beyond) in the Fable repo, so please make any PR towards that. Beyond will eventually be merged into `main` https://github.com/fable-compiler/Fable/pull/2640 to become Fable 4.0.0

This repo is (just) the Python binding for Fable, but it's sort of our own Fable Python repo, so we can discuss Python specific stuff here and add documentation etc even if the compiler itself lives somewhere else.

Some more info: https://github.com/fable-compiler/Fable/tree/beyond/src/Fable.Transforms/Python

Docs (wip, so not exposed yet): https://fable.io/Fable.Python/
