### ISSUE TITLE
aggressive inlining breaks `let mutable` semantics

### ISSUE THREAD

**Issue by thautwarm** [fable-compiler/Fable.Python#32]
(Sorry for these overwhelming issues... Just post them here and I can help)

Inlining let bindings in Fable seems ignoring the side-effect of evaluation. I've constructed a minimal repro:

```fsharp

type S() =
    let mutable f = []

    let call() =
        f <- 1 :: f
        [2]

    let main() =
        let xs = call() <-- has side effect here, modifying `f`
        f @ xs
 
```

`call()` will modify the value of `f`, hence the result is expected to be `[1] @ [2]` == `[1; 2]`.
 
However, running the generated python code gives `[2]`. The generated code is:

```python
class S:
    def __init__(self) -> None:
        self.f = empty()

def S__call(this: S) -> FSharpList[int]:
    this.f = cons(1, this.f)
    return singleton(2)


def S__main(this: S) -> FSharpList[int]:
    return append(this.f, S__call(this))   <----- this will get us unchanged `this.f`, which is incorrect 

```

P.S: I'm not sure if this is a Fable.Python specific issue.

**Comment by dbrattli** [comment]
Not sure what's going on here.  When I run the code I get `[1; 2]`. But my generated code looks correct. Not sure if this is something that have been fixed upstream (Fable).

```py
def expr_8() -> TypeInfo:
    return class_type("QuickTest.S", None, S)


class S:
    def __init__(self) -> None:
        self.f = empty()
    

S_reflection = expr_8

def S__ctor() -> S:
    return S()


def S__call(this: S) -> FSharpList[int]:
    this.f = cons(1, this.f)
    return singleton(2)


def S__main(this: S) -> FSharpList[int]:
    xs : FSharpList[int] = S__call(this)
    return append(this.f, xs)
```

**Comment by thautwarm** [comment]
Nice to see it gets fixed. May you please tell me your `fable-py` version? I tried `4.0.0-alpha-020` and `4.0.0-alpha-005` which are available on Nuget, but didn't get it correct..

**Comment by dbrattli** [comment]
Now I also tried `-20` and it fails here as well. The code I used was `beyond` branch. It get's updates from `main` now and then. 

To test code snippets with the latest compiler it's btw easy to use the `src/quicktest/QuickTest.fsproj` project in the Fable repo. Checkout `beyond`, replace `QuickTest.fs` with your code and run `dotnet fsi build.fsx quicktest-py` from the root of the repo.

You can also run without `fable-py` from a custom location by running `dotnet run . --project ../../../Fable/src/Fable.Cli --lang Python`. This will do the same as `fable-py` without using `fable-py`. Note that you need to modify `../../../Fable/src/Fable.Cli` to point to the Fable repo `src/Fable.cli` relative from where you are currently located.

**Comment by dbrattli** [comment]
PS: Would be great if you want to contribute this as a unit-test to e.g [`TestMisc.fs`](https://github.com/fable-compiler/Fable/blob/beyond/tests/Python/TestMisc.fs) so the bug doesn't come back. Python tests are btw now run as part of the CI for all of Fable.

**Comment by dbrattli** [comment]
Adding @alfonsogarciacaro @ncave that might have more info about this bug (which now looks to be resolved) by upstream fixes?

**Comment by thautwarm** [comment]
Thanks for this information. I'm going to make a PR for that unit-test.

**Comment by dbrattli** [comment]
Great! The Python tests can be run with `dotnet fsi build.fsx test-py`. They will btw output to `build/test/Python`. Thus if you tweak the Python code directly you can run a particular file directly using e.g `pytest build/tests/Python/test_misc.py`

**Comment by thautwarm** [comment]
Thanks for these kind instructions!

**Comment by dbrattli** [comment]
Forgot to say you need to generate the fable library before testing: `dotnet fsi build.fsx library-py`

**Comment by thautwarm** [comment]
Ahh, I didn't get the test pass on latest `beyond`.. Anyway I make a PR.

**Comment by thautwarm** [comment]
I add a control group in the PR:

```fsharp
    let runCase (l: int) (r: int) (expect: int) =
        let mutable left = 0
        let call() =
            left <- l
            r

        let run() =
            let right = call()
            left + right

       run() |> equal (left + right)

```

Such function works fine. Hope thishelp bug positioning.

**Comment by dbrattli** [comment]
FYI: note that things might be a little slow these days because of vacation. But failing unit-tests are a great contribution!

**Comment by dbrattli** [comment]
FYI: Looks like a problem upstream. The test fails for JavaScript as well: https://github.com/fable-compiler/Fable/pull/2687

**Comment by alfonsogarciacaro** [comment]
Thanks a lot @thautwarm for reporting and @dbrattli for helping isolate the issue! I've added a fix for Fable's `main` branch and I will port it to `beyond` so it works with Python too 👍

**Comment by dbrattli** [comment]
Thanks @alfonsogarciacaro 💯
