### ISSUE TITLE
Scripting support .fsx

### ISSUE THREAD

**Issue by jkone27** [fable-compiler/Fable.Python#33]
can this work with simple .fsx files as well?

i tried
```fsharp

#r "nuget: Fable.Python"
#r "nuget: Fable.Core.Experimental, 4.0.0-alpha-020"

open Fable.Core.Experimental
open Fable.Python.Json

let object = {| A=10; B=20; C="hello" |}

let result = json.dumps object


// dotnet tool install --global fable-py --version 4.0.0-alpha-020
```

![image](https://user-images.githubusercontent.com/10419217/147779216-84529b76-09fa-4c73-864a-7192ea48a424.png)

**Comment by dbrattli** [comment]
Sorry, nuget's in fsx scripts is afaik not supported by Fable. You will need to use a project file for now.

**Comment by jkone27** [comment]
maybe some community contributor could help add support for this? i think code would be more "python" like in a script, rather than in a project, also for pp coming from python that might look easier to adopt

**Comment by dbrattli** [comment]
This is supported. See https://github.com/fable-compiler/Fable/blob/snake_island/src/quicktest-py/quicktest.fsx
