### ISSUE TITLE
[DU] accessing tags failed.

### ISSUE THREAD

**Issue by thautwarm** [fable-compiler/Fable.Python#41]
In the latest version `0.0.26`, the following code crashes,
```F#
type a = A1 | A2 of int
let _ = printfn "%A" A1 (* any union data)
``

error message:

```python
  File "...\fable_modules\fable_library\types.py", line 51, in name
    return Union.cases()[self.tag]
TypeError: 'NoneType' object is not subscriptable
```

This is due to the change at https://github.com/dbrattli/Fable/blob/89a7b558f2249ba78a6c8d4ea671fb01a224f15d/src/fable-library-py/fable_library/types.py#L51 

```python
class Union(IComparable):
    def __init__(self):
   
    ...
       Union.cases()[self.tag]  # <--- here
```

`Union.cases` calls the abstract method, which simply returns `None`.

**Comment by thautwarm** [comment]
Could you explain a little about your intention for changing `self.cases()[self.tag]` to `Union.cases()[self.tag]`? I'd like to make a PR but without understanding your intention I might break such a large system unexpectedly..

**Comment by dbrattli** [comment]
Thanks for reporting. I was trying to fix a mypy reported error in the last line here:

```py
class Union(IComparable):
    def __init__(self):
        self.tag: int
        self.fields: List[Any] = []

    @abstractstaticmethod
    def cases() -> List[str]:
        ...

    @property
    def name(self) -> str:
        return self.cases()[self.tag]
```

> Attribute function "cases" with type "Callable[[], List[str]]" does not accept self argument mypy(error)

So this error is probably wrong? It's possible to call a static method from an instance!? O should we just convert to a normal instance (self) method instead. What do you think?

PS: `abstractstaticmethod` is btw deprected: https://docs.python.org/3/library/abc.html#abc.abstractstaticmethod

**Comment by thautwarm** [comment]
changing it to a combination of `@staticmethod` and `abstractmethod` should suffice.

```python
@staticmethod
@abstractmethod
def cases() -> List[str]:
        raise NotImplementedError
```
