### ISSUE TITLE
How to locally build a fable-py CLI tool?

### ISSUE THREAD

**Issue by thautwarm** [fable-compiler/Fable.Python#45]
The build instructions from [README](https://github.com/fable-compiler/Fable/blob/beyond/README.md#building) do not produce a nuget package that contains fable-library-py.

Could you provide some extra instructions for making local releases?

**Comment by dbrattli** [comment]
I have never done this, and not sure it's possible. Running `fable-py` global tool or `dotnet fable-py` local tools is exactly the same as running `dotnet run --project ../../../Fable/src/Fable.Cli --lang Python` (use correct path for your Fable dir). So you could basically just make yourself a shell alias.

**Comment by thautwarm** [comment]
It's possible to create a CLI tool, but it's always accessing FableLib from "../../../../"...
I tried this: [dotnet/sdk#13429](https://github.com/dotnet/sdk/issues/13429#issuecomment-733872976) after creating a nuget package for `Fable.CLI`, but it didn't work for me and simply installed fable from the remote.
Anyway it's not that necessary. We might have compilers purely running in JS/PY for Fable.Python in the future.
