### ISSUE TITLE
DUs are not hashable 

### ISSUE THREAD

**Issue by thautwarm** [fable-compiler/Fable.Python#47]
```python
fable_modules\fable_library\types.py", line 74, in __hash__
    return hash([hash(self.tag), *hashes])
```

We cannot hash a Python list as it is mutable. Tuples are hashable if and only if all the elements are hashable. Changing the code to `return hash( (hash(self.tag), *hashes) )`  will suffice. 

I can make a PR soon later.

**Comment by dbrattli** [comment]
Yes, I just discovered the same with TypeInfo

**Comment by dbrattli** [comment]
Closing since this issue should be fixed

**Comment by dbrattli** [comment]
Closing since this issue should be fixed
