### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by jkone27** [fable-compiler/Fable.Python#51]
i would love to try this out!

it seems docs still point to the JS version, maybe a good "up for grabs" or "first issue" could be extending/updating fable python docs!

Thanks a lot for this awesome project ❤️ !

**Comment by dbrattli** [comment]
Yes, the plan is to have separate docs for Fable.Python as a [Jupyter book](https://jupyterbook.org/intro.html) that is written as a in [MyST](https://myst-parser.readthedocs.io/en/latest/). This will make it easy to mix code and docs and will actually make it possible to have [executable content](https://jupyterbook.org/content/executable/index.html) and even [live code](https://jupyterbook.org/interactive/thebe.html) cells. It would be awesome if you would like to help out! The source for the docs is at https://github.com/fable-compiler/Fable.Python/tree/main/docs-src

**Comment by dbrattli** [comment]
I have updated the docs so should be more references to Python than JS now. Please open PR's preferably for any issues with the docs.
