### ISSUE TITLE
Console.ReadLine is not supported by Fable

### ISSUE THREAD

**Issue by WhiteBlackGoose** [fable-compiler/Fable.Python#54]
Hi!

First, thanks for this great work!

Now, I'm trying to compile a simple hello world, but System.Console.ReadLine is not supported. Is there some bold reason for it, or it's just not implemented yet?

**Comment by WhiteBlackGoose** [comment]
Interestingly I can't even find the sources where you generate code for other functions XD

**Comment by dbrattli** [comment]
Thanks for the issue. I have added Readline to Fable (where the sources actually live). See the mention above.

**Comment by WhiteBlackGoose** [comment]
Thanks! Awesome!
