### ISSUE TITLE
Builtins.builtins.open has incorrect definition

### ISSUE THREAD

**Issue by teknikal-wizard** [fable-compiler/Fable.Python#79]
I am working through converting an ML sample to Fable Python, and I need to open a CSV file.

It seems the proper Python way to do that is to use the [csv module](https://docs.python.org/3.9/library/csv.html?highlight=csv%20open#examples). The csv.reader function requires a file which they load with the built in [open ](https://docs.python.org/3.9/library/functions.html#open) function.

I found that function in Fable.Python.Builtins.builtins has an `open` function, but it has no intellisense and shows an error when I try to use it.

![image](https://user-images.githubusercontent.com/66260121/198675353-e504d01f-874e-4d8e-bf90-63a444a6170f.png)

**Comment by dbrattli** [comment]
Yes, `open` is a keyword in F#. That's why you get that message. Look at line 4, 5 and 6. We cannot use that name so the open function from Python have been named ` ``open`` `.  E.g try:

```fs
let result = builtins.``open``("test.txt", OpenTextMode.Write)
```

**Comment by dbrattli** [comment]
Another option is to use `System.IO.ReadAllText` which is supported by Python

**Comment by teknikal-wizard** [comment]
Ah of course! Thank you :)
