### ISSUE TITLE
Lower FSharp.Core dependency from 6.0.0 to 4.7.2 for better compatibility

### ISSUE THREAD

**Issue by Zaid-Ajaj** [fable-compiler/Fable.Python#85]
Reopening #19 because the same issue has surfaced. Does Fable.Python need _latest_ FSharp.Core? If not, please consider lowering it to `>= 4.7.2`

Currently Fable.Python v4.0.0-theta-003 requires FSharp.Core v6.0.6

**Comment by dbrattli** [comment]
@Zaid-Ajaj Thanks for reopening. I must admit that I have no clue why it requires FSharp.Core v6.0.0 when the dependency is already specified as >= 4.7.2:

https://github.com/fable-compiler/Fable.Python/blob/main/paket.dependencies#L7

I'll try to set `lowest_matching: true` to see if that helps.

**Comment by dbrattli** [comment]
@Zaid-Ajaj This looks better right? https://www.nuget.org/packages/Fable.Python/4.0.0-theta-004#dependencies-body-tab

**Comment by Zaid-Ajaj** [comment]
@dbrattli Much better 😄 thank you!
