### ISSUE TITLE
PyPI fable_library out-of-date?

### ISSUE THREAD

**Issue by thautwarm** [fable-compiler/Fable.Python#87]
Hello! I'd like to try Fable.Python again as it very much fits my current use case.

When I tried importing `fable_library` from PyPI (so that different projects can use the same `fable_library` and data types can shared), the latest Fable.Python gave me this error:

```python
ImportError: cannot import name 'int64' from 'fable_library.types' (...\Miniforge\lib\site-packages\fable_library\types.py)
```

`int64` is defined in the latest `fable_library`: https://github.com/fable-compiler/Fable/tree/main/src/fable-library-py, should we create a latest PyPI release for `fable_library`?

**Comment by dbrattli** [comment]
@thautwarm I have updated the library. Please try again.
